import "./globals.css";
import { moreSugar } from "@/styles/fonts";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${moreSugar.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
